---
AWSTemplateFormatVersion: 2010-09-09

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Type
        Parameters:
          - EnvironmentType

    ParameterLabels:
      EnvironmentType:
        default: Environment Type


Parameters:
  EnvironmentType:
    Type: String
    Description: Environment of Deployment
    AllowedValues: [ 'dev', 'qa', 'uat', 'int', 'production' ]
    Default: 'dev'


Conditions:
  EnvironmentProd:
    !Equals [ !Ref EnvironmentType, "production" ]

Resources:
  realtimedatapipelineec2instance:
      Type: AWS::CloudFormation::Stack
      Properties:
        Parameters:
          KeyName: 'aws-lab-real-time-datapipeline'
          InstanceType: 't2.micro'
        TemplateURL: deployment/ec2_deployment.yaml
