---
AWSTemplateFormatVersion: 2010-09-09

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Type
        Parameters:
          - EnvironmentType
      - Label:
          default: AWS resources
        Parameters:
          - BucketName

    ParameterLabels:
      EnvironmentType:
        default: Environment Type
      BucketName:
        default: Bucketname to Upload Lambda Zips


Parameters:
  EnvironmentType:
    Type: String
    Description: Environment of Deployment
    AllowedValues: [ 'dev', 'qa', 'uat', 'int', 'production' ]
    Default: 'dev'
  BucketName:
    Description: Bucketname to Upload Zips
    Type: String


Conditions:
  EnvironmentProd:
    !Equals [ !Ref EnvironmentType, "production" ]

Resources:
  sourcebucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        BucketName: 'source-real-time'
#        EncryptionKeyArn: !ImportValue s3-encryption-key
#      TemplateURL: AwsResources/01_s3_bucket.yaml
